#! /bin/bash

MMDIR="$HOME/GoogleDrive/Docear/Tasklog"
MASTERMM="$MMDIR/TaskLog.mm"
OLDMM="$MMDIR/$(date -dlast-monday +%Y%m%d)Workweek.mm"
NEWNAME="$(date +%Y%m%d)Weekend"
NEWMM="$MMDIR/$(date +%Y%m%d)Weekend.mm"

echo $OLDMM
echo $NEWMM

# Merge checked with master mindmap
mynd.py -m $MASTERMM $OLDMM
# Prune and write to new mindmap
mynd.py -u -w $NEWMM -n $NEWNAME $OLDMM
