#! /bin/bash

MMDIR="$HOME/GoogleDrive/Docear/Tasklog"
OLDMM="$MMDIR/$(date -dlast-monday +%Y%m%d)Workweek.mm"
NEWMM="$MMDIR/$(date +%Y%m%d)Weekend.mm"

echo $OLDMM
echo $NEWMM

mynd.py -u -w $NEWMM $OLDMM
